apiVersion: apps/v1
kind: Deployment
metadata:
  name: restweb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restweb-service
  template:
    metadata:
      labels:
        app: restweb-service
    spec:
      containers:
        - name: restweb-service
          image: restweb-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080